server:
  port: 8081
  location: "http://43.129.171.44"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_blog?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: "1819891412s"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  cors:
#    webflux:
#      allowed-origins: http://localhost:8080
#      allowed-methods: GET,POST,PUT,DELETE
#      allowed-headers: Content-Type,Authorization
#      allow-credentials: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user:
  adminId: "1771163535399747585"

#file:
#  path: "E:/ImgData/Blog/"

file:
  path: "/usr/local/data/img/"

img:
  downloadPath: "${server.location}:${server.port}/img/download?fileName="

