server:
  port: 8081
  location: "43.129.171.44"
spring:
  redis:
    database: 0
    host: "localhost"
    port: 6379
    password: "1819891412"
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    token: #token超时时间
      expiration-time: 1800
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_blog?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: "1819891412s"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  cors:
#    webflux:
#      allowed-origins: http://localhost:8080
#      allowed-methods: GET,POST,PUT,DELETE
#      allowed-headers: Content-Type,Authorization
#      allow-credentials: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user:
  adminId: "1771163535399747585"

#file:
#  path: "E:/ImgData/Blog/"

file:
  path: "/usr/local/data/img/"

img:
  downloadPath: "http://${server.location}:${server.port}/img/download?fileName="

